# Generated by Django 5.1.3 on 2024-12-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="SEM_SPI_List",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
