# Generated by Django 5.1.3 on 2024-12-06 11:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_home", "0002_alter_account_sem_spi_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="created_on",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
